ARG version 
FROM almalinux:${version:-8}
#RUN cat /etc/*release
ARG COURSE=Docker
ARG TRAINER=Sivakumar
RUN echo "Course Name is ${COURSE}"
RUN echo "Trainer Name is ${TRAINER}"
CMD [ "sleep", "100" ]